### ISSUE TITLE
How to call function of a class/Component, for the do function of Idle class 

### ISSUE THREAD

**Issue by ShaileshBhatNP** [harunurhan/idlejs#4]
I need to call like below

```
const idle = new Idle()
  .whenNotInteractive()
  .within(5,1000)
  //.do(() => console.log('IDLE'))
  .do(() => LoginPage)  //Need to call LoginPage
  .start();
```

Is it possible to achieve my requirement using this plugin..?

**Comment by harunurhan** [comment]
Well, `do` takes a js function where you can do anything you want. You want to route the LoginPage right? If you give me more details about your application like which framework you use, I can try to help. 

(Sorry for the late answer, apparently notification settings were disabled 😞)

**Comment by ShaileshBhatNP** [comment]
Ionic Framework+Angular4  framework

**Comment by harunurhan** [comment]
I assume that you have `@angular/router` set up. 

- Inject [`Router`](https://angular.io/api/router/Router) where you create you `Idle` object
- Then `.do(() => { this.router.navigateByUrl('/login'); })`
